changelog:
  categories:
    - title: Security 🛡️
      labels:
        - Security
    - title: Breaking Changes 🛠
      labels:
        - Breaking change
    - title: New Features 💎
      labels:
        - Feature
    - title: Fixes ⛑️
      labels:
        - Fix
    - title: Other Changes 🖇️
      labels:
        - "*"