<?php

namespace Dbout\WpOrm\Builders;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Query\Builder as QueryBuilder;

/**
 * Class PostTypeBuilder
 * @package Dbout\WpOrm\Builders
 */
class PostTypeBuilder extends Builder
{



    public function select($columns = ['*'])
    {
        var_dump($this); die;
        return parent::select($columns); // TODO: Change the autogenerated stub
    }

}