name: ci

on:
  pull_request:

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          tools: composer:v2

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: PHPCsFixer
        run: vendor/bin/php-cs-fixer fix --verbose --diff --dry-run

      - name: PHPStan
        run: vendor/bin/phpstan analyse -c phpstan.neon

      - name: Rector
        run: vendor/bin/rector process src --dry-run