name: Coding Styles

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  codingStyle:
    name: "Coding Style"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repo"
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: "Configure PHP"
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # v2
        with:
          php-version: 8.3
          tools: composer:v2

      - name: "Install dependencies"
        run: composer install --prefer-dist --no-progress

      - name: "PHPCsFixer"
        run: composer csFixer

      - name: Rector
        run: composer rector

      - name: "PHPStan Analyse"
        run: composer phpstan
